global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape our FastAPI service
  - job_name: "api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]
